services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${SECRET_KEY?Variable SECRET_KEY not set}
    volumes:
      - ../storage/redis_cache:/data
    restart: always
    networks:
      - ai_service
