services:
  neo4j_db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/${SECRET_KEY?Variable SECRET_KEY not set}
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      # NEO4J_dbms_default__database: neo4j
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      # NEO4J_server_memory_heap_initial__size: 6G
      # NEO4J_server_memory_heap_max__size: 6G
    volumes:
      - ../storage/neo4j_data:/data
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    restart: always
    networks:
      - ai_service
