services:
  qdrant:
    image: qdrant/qdrant:latest
    environment:
      # - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY?Variable QDRANT_API_KEY is not set}
      QDRANT__TELEMETRY_DISABLED: true
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../storage/qdrant_data:/qdrant/storage
    restart: always
    networks:
      - ai_service
