services:
  minio:
    image: minio/minio
    ports:
      - "5100:9000"
      - "5101:9001"
    volumes:
      - ../storage/minio_data:/data
    environment:
      MINIO_ROOT_USER: ${ACCESS_KEY?Variable ACCESS_KEY not set}
      MINIO_ROOT_PASSWORD: ${SECRET_KEY?Variable SECRET_KEY not set}
    command: server --console-address ":9001" /data
    networks:
      - ai_service
